# Generated by Django 5.2.4 on 2025-08-12 22:56

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('capacity', models.IntegerField()),
                ('rows', models.IntegerField()),
                ('columns', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=10)),
                ('departure_city', models.CharField(max_length=100)),
                ('departure_date', models.DateField()),
                ('departure_time', models.TimeField()),
                ('arrival_city', models.CharField(max_length=100)),
                ('arrival_date', models.DateField()),
                ('arrival_time', models.TimeField()),
                ('duration', models.DurationField(default=datetime.timedelta(0))),
                ('status', models.CharField(choices=[('on_time', 'A tiempo'), ('delayed', 'Retrasado'), ('cancelled', 'Cancelado')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='flight.plane')),
            ],
        ),
    ]
